#! /bin/sh

sxhkd &

bspc monitor eDP-1  -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI-1  -d 11 12 13 14 1 5 16 17 18 19 20

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
xrdb ~/.Xresources
wal -i ~/.wallpaper/wallpaper.jpg --backend wal
feh --bg-fill .wallpaper/wallpaper.jpg --bg-fill .wallpaper/test.jpg 

~/scripts/startup
~/scripts/pulse-volume-monitor.py | xob -s bspwm
